// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/inv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FromPeer  string                 `protobuf:"bytes,2,opt,name=from_peer,json=fromPeer,proto3" json:"from_peer,omitempty"`
	ToPeer    string                 `protobuf:"bytes,3,opt,name=to_peer,json=toPeer,proto3" json:"to_peer,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_SignalChange
	//	*Envelope_SignalSweep
	//	*Envelope_QueryAsk
	//	*Envelope_QueryRespond
	//	*Envelope_TraceResolveReq
	//	*Envelope_TraceResolveResp
	//	*Envelope_Ack
	//	*Envelope_Error
	//	*Envelope_ProposalCreate
	//	*Envelope_ProposalVote
	//	*Envelope_ProposalResult
	//	*Envelope_TallyRequest
	//	*Envelope_PeerHandshake
	//	*Envelope_ChallengeCreate
	//	*Envelope_ChallengeResponse
	//	*Envelope_ChallengeVote
	//	*Envelope_ChallengeResult
	//	*Envelope_PairInvite
	//	*Envelope_PairAccept
	//	*Envelope_PairEnd
	//	*Envelope_PairEvent
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_inv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetFromPeer() string {
	if x != nil {
		return x.FromPeer
	}
	return ""
}

func (x *Envelope) GetToPeer() string {
	if x != nil {
		return x.ToPeer
	}
	return ""
}

func (x *Envelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignalChange() *SignalChange {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SignalChange); ok {
			return x.SignalChange
		}
	}
	return nil
}

func (x *Envelope) GetSignalSweep() *SignalSweep {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SignalSweep); ok {
			return x.SignalSweep
		}
	}
	return nil
}

func (x *Envelope) GetQueryAsk() *QueryAsk {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_QueryAsk); ok {
			return x.QueryAsk
		}
	}
	return nil
}

func (x *Envelope) GetQueryRespond() *QueryRespond {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_QueryRespond); ok {
			return x.QueryRespond
		}
	}
	return nil
}

func (x *Envelope) GetTraceResolveReq() *TraceResolveRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TraceResolveReq); ok {
			return x.TraceResolveReq
		}
	}
	return nil
}

func (x *Envelope) GetTraceResolveResp() *TraceResolveResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TraceResolveResp); ok {
			return x.TraceResolveResp
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetProposalCreate() *ProposalCreate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ProposalCreate); ok {
			return x.ProposalCreate
		}
	}
	return nil
}

func (x *Envelope) GetProposalVote() *ProposalVote {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ProposalVote); ok {
			return x.ProposalVote
		}
	}
	return nil
}

func (x *Envelope) GetProposalResult() *ProposalResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ProposalResult); ok {
			return x.ProposalResult
		}
	}
	return nil
}

func (x *Envelope) GetTallyRequest() *TallyRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TallyRequest); ok {
			return x.TallyRequest
		}
	}
	return nil
}

func (x *Envelope) GetPeerHandshake() *PeerHandshake {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PeerHandshake); ok {
			return x.PeerHandshake
		}
	}
	return nil
}

func (x *Envelope) GetChallengeCreate() *ChallengeCreate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ChallengeCreate); ok {
			return x.ChallengeCreate
		}
	}
	return nil
}

func (x *Envelope) GetChallengeResponse() *ChallengeResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ChallengeResponse); ok {
			return x.ChallengeResponse
		}
	}
	return nil
}

func (x *Envelope) GetChallengeVote() *ChallengeVote {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ChallengeVote); ok {
			return x.ChallengeVote
		}
	}
	return nil
}

func (x *Envelope) GetChallengeResult() *ChallengeResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ChallengeResult); ok {
			return x.ChallengeResult
		}
	}
	return nil
}

func (x *Envelope) GetPairInvite() *PairInvite {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PairInvite); ok {
			return x.PairInvite
		}
	}
	return nil
}

func (x *Envelope) GetPairAccept() *PairAccept {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PairAccept); ok {
			return x.PairAccept
		}
	}
	return nil
}

func (x *Envelope) GetPairEnd() *PairEnd {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PairEnd); ok {
			return x.PairEnd
		}
	}
	return nil
}

func (x *Envelope) GetPairEvent() *PairEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PairEvent); ok {
			return x.PairEvent
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_SignalChange struct {
	SignalChange *SignalChange `protobuf:"bytes,10,opt,name=signal_change,json=signalChange,proto3,oneof"`
}

type Envelope_SignalSweep struct {
	SignalSweep *SignalSweep `protobuf:"bytes,11,opt,name=signal_sweep,json=signalSweep,proto3,oneof"`
}

type Envelope_QueryAsk struct {
	QueryAsk *QueryAsk `protobuf:"bytes,14,opt,name=query_ask,json=queryAsk,proto3,oneof"`
}

type Envelope_QueryRespond struct {
	QueryRespond *QueryRespond `protobuf:"bytes,15,opt,name=query_respond,json=queryRespond,proto3,oneof"`
}

type Envelope_TraceResolveReq struct {
	TraceResolveReq *TraceResolveRequest `protobuf:"bytes,16,opt,name=trace_resolve_req,json=traceResolveReq,proto3,oneof"`
}

type Envelope_TraceResolveResp struct {
	TraceResolveResp *TraceResolveResponse `protobuf:"bytes,17,opt,name=trace_resolve_resp,json=traceResolveResp,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Ack `protobuf:"bytes,20,opt,name=ack,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,21,opt,name=error,proto3,oneof"`
}

type Envelope_ProposalCreate struct {
	ProposalCreate *ProposalCreate `protobuf:"bytes,22,opt,name=proposal_create,json=proposalCreate,proto3,oneof"`
}

type Envelope_ProposalVote struct {
	ProposalVote *ProposalVote `protobuf:"bytes,23,opt,name=proposal_vote,json=proposalVote,proto3,oneof"`
}

type Envelope_ProposalResult struct {
	ProposalResult *ProposalResult `protobuf:"bytes,24,opt,name=proposal_result,json=proposalResult,proto3,oneof"`
}

type Envelope_TallyRequest struct {
	TallyRequest *TallyRequest `protobuf:"bytes,25,opt,name=tally_request,json=tallyRequest,proto3,oneof"`
}

type Envelope_PeerHandshake struct {
	PeerHandshake *PeerHandshake `protobuf:"bytes,26,opt,name=peer_handshake,json=peerHandshake,proto3,oneof"`
}

type Envelope_ChallengeCreate struct {
	ChallengeCreate *ChallengeCreate `protobuf:"bytes,30,opt,name=challenge_create,json=challengeCreate,proto3,oneof"`
}

type Envelope_ChallengeResponse struct {
	ChallengeResponse *ChallengeResponse `protobuf:"bytes,31,opt,name=challenge_response,json=challengeResponse,proto3,oneof"`
}

type Envelope_ChallengeVote struct {
	ChallengeVote *ChallengeVote `protobuf:"bytes,32,opt,name=challenge_vote,json=challengeVote,proto3,oneof"`
}

type Envelope_ChallengeResult struct {
	ChallengeResult *ChallengeResult `protobuf:"bytes,33,opt,name=challenge_result,json=challengeResult,proto3,oneof"`
}

type Envelope_PairInvite struct {
	PairInvite *PairInvite `protobuf:"bytes,40,opt,name=pair_invite,json=pairInvite,proto3,oneof"`
}

type Envelope_PairAccept struct {
	PairAccept *PairAccept `protobuf:"bytes,41,opt,name=pair_accept,json=pairAccept,proto3,oneof"`
}

type Envelope_PairEnd struct {
	PairEnd *PairEnd `protobuf:"bytes,42,opt,name=pair_end,json=pairEnd,proto3,oneof"`
}

type Envelope_PairEvent struct {
	PairEvent *PairEvent `protobuf:"bytes,43,opt,name=pair_event,json=pairEvent,proto3,oneof"`
}

func (*Envelope_SignalChange) isEnvelope_Payload() {}

func (*Envelope_SignalSweep) isEnvelope_Payload() {}

func (*Envelope_QueryAsk) isEnvelope_Payload() {}

func (*Envelope_QueryRespond) isEnvelope_Payload() {}

func (*Envelope_TraceResolveReq) isEnvelope_Payload() {}

func (*Envelope_TraceResolveResp) isEnvelope_Payload() {}

func (*Envelope_Ack) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

func (*Envelope_ProposalCreate) isEnvelope_Payload() {}

func (*Envelope_ProposalVote) isEnvelope_Payload() {}

func (*Envelope_ProposalResult) isEnvelope_Payload() {}

func (*Envelope_TallyRequest) isEnvelope_Payload() {}

func (*Envelope_PeerHandshake) isEnvelope_Payload() {}

func (*Envelope_ChallengeCreate) isEnvelope_Payload() {}

func (*Envelope_ChallengeResponse) isEnvelope_Payload() {}

func (*Envelope_ChallengeVote) isEnvelope_Payload() {}

func (*Envelope_ChallengeResult) isEnvelope_Payload() {}

func (*Envelope_PairInvite) isEnvelope_Payload() {}

func (*Envelope_PairAccept) isEnvelope_Payload() {}

func (*Envelope_PairEnd) isEnvelope_Payload() {}

func (*Envelope_PairEvent) isEnvelope_Payload() {}

type SignalChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceItemId  string                 `protobuf:"bytes,1,opt,name=source_item_id,json=sourceItemId,proto3" json:"source_item_id,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetItemId  string                 `protobuf:"bytes,3,opt,name=target_item_id,json=targetItemId,proto3" json:"target_item_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalChange) Reset() {
	*x = SignalChange{}
	mi := &file_proto_inv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalChange) ProtoMessage() {}

func (x *SignalChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalChange.ProtoReflect.Descriptor instead.
func (*SignalChange) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{1}
}

func (x *SignalChange) GetSourceItemId() string {
	if x != nil {
		return x.SourceItemId
	}
	return ""
}

func (x *SignalChange) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *SignalChange) GetTargetItemId() string {
	if x != nil {
		return x.TargetItemId
	}
	return ""
}

func (x *SignalChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SignalSweep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExternalRef    string                 `protobuf:"bytes,1,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	SourceNodeId   string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	MatchedItemIds []string               `protobuf:"bytes,3,rep,name=matched_item_ids,json=matchedItemIds,proto3" json:"matched_item_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignalSweep) Reset() {
	*x = SignalSweep{}
	mi := &file_proto_inv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalSweep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalSweep) ProtoMessage() {}

func (x *SignalSweep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalSweep.ProtoReflect.Descriptor instead.
func (*SignalSweep) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{2}
}

func (x *SignalSweep) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *SignalSweep) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *SignalSweep) GetMatchedItemIds() []string {
	if x != nil {
		return x.MatchedItemIds
	}
	return nil
}

type QueryAsk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	AskerId       string                 `protobuf:"bytes,2,opt,name=asker_id,json=askerId,proto3" json:"asker_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAsk) Reset() {
	*x = QueryAsk{}
	mi := &file_proto_inv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAsk) ProtoMessage() {}

func (x *QueryAsk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAsk.ProtoReflect.Descriptor instead.
func (*QueryAsk) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAsk) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryAsk) GetAskerId() string {
	if x != nil {
		return x.AskerId
	}
	return ""
}

func (x *QueryAsk) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *QueryAsk) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type QueryRespond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	ResponderId   string                 `protobuf:"bytes,2,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	IsAi          bool                   `protobuf:"varint,4,opt,name=is_ai,json=isAi,proto3" json:"is_ai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRespond) Reset() {
	*x = QueryRespond{}
	mi := &file_proto_inv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRespond) ProtoMessage() {}

func (x *QueryRespond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRespond.ProtoReflect.Descriptor instead.
func (*QueryRespond) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRespond) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryRespond) GetResponderId() string {
	if x != nil {
		return x.ResponderId
	}
	return ""
}

func (x *QueryRespond) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QueryRespond) GetIsAi() bool {
	if x != nil {
		return x.IsAi
	}
	return false
}

type TraceResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceResolveRequest) Reset() {
	*x = TraceResolveRequest{}
	mi := &file_proto_inv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceResolveRequest) ProtoMessage() {}

func (x *TraceResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceResolveRequest.ProtoReflect.Descriptor instead.
func (*TraceResolveRequest) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{5}
}

func (x *TraceResolveRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type TraceResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Vertical      string                 `protobuf:"bytes,6,opt,name=vertical,proto3" json:"vertical,omitempty"`
	Found         bool                   `protobuf:"varint,7,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceResolveResponse) Reset() {
	*x = TraceResolveResponse{}
	mi := &file_proto_inv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceResolveResponse) ProtoMessage() {}

func (x *TraceResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceResolveResponse.ProtoReflect.Descriptor instead.
func (*TraceResolveResponse) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{6}
}

func (x *TraceResolveResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *TraceResolveResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TraceResolveResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TraceResolveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TraceResolveResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TraceResolveResponse) GetVertical() string {
	if x != nil {
		return x.Vertical
	}
	return ""
}

func (x *TraceResolveResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefMessageId  string                 `protobuf:"bytes,1,opt,name=ref_message_id,json=refMessageId,proto3" json:"ref_message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_inv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetRefMessageId() string {
	if x != nil {
		return x.RefMessageId
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefMessageId  string                 `protobuf:"bytes,1,opt,name=ref_message_id,json=refMessageId,proto3" json:"ref_message_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_inv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{8}
}

func (x *Error) GetRefMessageId() string {
	if x != nil {
		return x.RefMessageId
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PeerHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Vertical      string                 `protobuf:"bytes,4,opt,name=vertical,proto3" json:"vertical,omitempty"`
	Project       string                 `protobuf:"bytes,5,opt,name=project,proto3" json:"project,omitempty"`
	Owner         string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	IsAi          bool                   `protobuf:"varint,7,opt,name=is_ai,json=isAi,proto3" json:"is_ai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerHandshake) Reset() {
	*x = PeerHandshake{}
	mi := &file_proto_inv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerHandshake) ProtoMessage() {}

func (x *PeerHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerHandshake.ProtoReflect.Descriptor instead.
func (*PeerHandshake) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{9}
}

func (x *PeerHandshake) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerHandshake) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerHandshake) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerHandshake) GetVertical() string {
	if x != nil {
		return x.Vertical
	}
	return ""
}

func (x *PeerHandshake) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *PeerHandshake) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PeerHandshake) GetIsAi() bool {
	if x != nil {
		return x.IsAi
	}
	return false
}

type ProposalCreate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposalId      string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ProposerPeer    string                 `protobuf:"bytes,5,opt,name=proposer_peer,json=proposerPeer,proto3" json:"proposer_peer,omitempty"`
	OwnerPeer       string                 `protobuf:"bytes,6,opt,name=owner_peer,json=ownerPeer,proto3" json:"owner_peer,omitempty"`
	AffectedItemIds []string               `protobuf:"bytes,7,rep,name=affected_item_ids,json=affectedItemIds,proto3" json:"affected_item_ids,omitempty"`
	Deadline        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProposalCreate) Reset() {
	*x = ProposalCreate{}
	mi := &file_proto_inv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalCreate) ProtoMessage() {}

func (x *ProposalCreate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalCreate.ProtoReflect.Descriptor instead.
func (*ProposalCreate) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{10}
}

func (x *ProposalCreate) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *ProposalCreate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProposalCreate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposalCreate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProposalCreate) GetProposerPeer() string {
	if x != nil {
		return x.ProposerPeer
	}
	return ""
}

func (x *ProposalCreate) GetOwnerPeer() string {
	if x != nil {
		return x.OwnerPeer
	}
	return ""
}

func (x *ProposalCreate) GetAffectedItemIds() []string {
	if x != nil {
		return x.AffectedItemIds
	}
	return nil
}

func (x *ProposalCreate) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type ProposalVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	VoterPeer     string                 `protobuf:"bytes,2,opt,name=voter_peer,json=voterPeer,proto3" json:"voter_peer,omitempty"`
	VoterId       string                 `protobuf:"bytes,3,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	Decision      string                 `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	IsAi          bool                   `protobuf:"varint,6,opt,name=is_ai,json=isAi,proto3" json:"is_ai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalVote) Reset() {
	*x = ProposalVote{}
	mi := &file_proto_inv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalVote) ProtoMessage() {}

func (x *ProposalVote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalVote.ProtoReflect.Descriptor instead.
func (*ProposalVote) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{11}
}

func (x *ProposalVote) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *ProposalVote) GetVoterPeer() string {
	if x != nil {
		return x.VoterPeer
	}
	return ""
}

func (x *ProposalVote) GetVoterId() string {
	if x != nil {
		return x.VoterId
	}
	return ""
}

func (x *ProposalVote) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ProposalVote) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProposalVote) GetIsAi() bool {
	if x != nil {
		return x.IsAi
	}
	return false
}

type ProposalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	VotesFor      int32                  `protobuf:"varint,3,opt,name=votes_for,json=votesFor,proto3" json:"votes_for,omitempty"`
	VotesAgainst  int32                  `protobuf:"varint,4,opt,name=votes_against,json=votesAgainst,proto3" json:"votes_against,omitempty"`
	TotalEligible int32                  `protobuf:"varint,5,opt,name=total_eligible,json=totalEligible,proto3" json:"total_eligible,omitempty"`
	OwnerVetoed   bool                   `protobuf:"varint,6,opt,name=owner_vetoed,json=ownerVetoed,proto3" json:"owner_vetoed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalResult) Reset() {
	*x = ProposalResult{}
	mi := &file_proto_inv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalResult) ProtoMessage() {}

func (x *ProposalResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalResult.ProtoReflect.Descriptor instead.
func (*ProposalResult) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{12}
}

func (x *ProposalResult) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *ProposalResult) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ProposalResult) GetVotesFor() int32 {
	if x != nil {
		return x.VotesFor
	}
	return 0
}

func (x *ProposalResult) GetVotesAgainst() int32 {
	if x != nil {
		return x.VotesAgainst
	}
	return 0
}

func (x *ProposalResult) GetTotalEligible() int32 {
	if x != nil {
		return x.TotalEligible
	}
	return 0
}

func (x *ProposalResult) GetOwnerVetoed() bool {
	if x != nil {
		return x.OwnerVetoed
	}
	return false
}

type TallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TallyRequest) Reset() {
	*x = TallyRequest{}
	mi := &file_proto_inv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TallyRequest) ProtoMessage() {}

func (x *TallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TallyRequest.ProtoReflect.Descriptor instead.
func (*TallyRequest) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{13}
}

func (x *TallyRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

type ChallengeCreate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId     string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Kind            string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ChallengerPeer  string                 `protobuf:"bytes,3,opt,name=challenger_peer,json=challengerPeer,proto3" json:"challenger_peer,omitempty"`
	ChallengedPeer  string                 `protobuf:"bytes,4,opt,name=challenged_peer,json=challengedPeer,proto3" json:"challenged_peer,omitempty"`
	TargetItemId    string                 `protobuf:"bytes,5,opt,name=target_item_id,json=targetItemId,proto3" json:"target_item_id,omitempty"`
	TargetTraceId   string                 `protobuf:"bytes,6,opt,name=target_trace_id,json=targetTraceId,proto3" json:"target_trace_id,omitempty"`
	Reason          string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Evidence        string                 `protobuf:"bytes,8,opt,name=evidence,proto3" json:"evidence,omitempty"`
	DeadlineSeconds int64                  `protobuf:"varint,9,opt,name=deadline_seconds,json=deadlineSeconds,proto3" json:"deadline_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChallengeCreate) Reset() {
	*x = ChallengeCreate{}
	mi := &file_proto_inv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeCreate) ProtoMessage() {}

func (x *ChallengeCreate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeCreate.ProtoReflect.Descriptor instead.
func (*ChallengeCreate) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{14}
}

func (x *ChallengeCreate) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeCreate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ChallengeCreate) GetChallengerPeer() string {
	if x != nil {
		return x.ChallengerPeer
	}
	return ""
}

func (x *ChallengeCreate) GetChallengedPeer() string {
	if x != nil {
		return x.ChallengedPeer
	}
	return ""
}

func (x *ChallengeCreate) GetTargetItemId() string {
	if x != nil {
		return x.TargetItemId
	}
	return ""
}

func (x *ChallengeCreate) GetTargetTraceId() string {
	if x != nil {
		return x.TargetTraceId
	}
	return ""
}

func (x *ChallengeCreate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ChallengeCreate) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *ChallengeCreate) GetDeadlineSeconds() int64 {
	if x != nil {
		return x.DeadlineSeconds
	}
	return 0
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Evidence      string                 `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Justification string                 `protobuf:"bytes,3,opt,name=justification,proto3" json:"justification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_proto_inv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{15}
}

func (x *ChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeResponse) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *ChallengeResponse) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

type ChallengeVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	VoterPeer     string                 `protobuf:"bytes,2,opt,name=voter_peer,json=voterPeer,proto3" json:"voter_peer,omitempty"`
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	IsAi          bool                   `protobuf:"varint,5,opt,name=is_ai,json=isAi,proto3" json:"is_ai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeVote) Reset() {
	*x = ChallengeVote{}
	mi := &file_proto_inv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeVote) ProtoMessage() {}

func (x *ChallengeVote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeVote.ProtoReflect.Descriptor instead.
func (*ChallengeVote) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{16}
}

func (x *ChallengeVote) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeVote) GetVoterPeer() string {
	if x != nil {
		return x.VoterPeer
	}
	return ""
}

func (x *ChallengeVote) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ChallengeVote) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ChallengeVote) GetIsAi() bool {
	if x != nil {
		return x.IsAi
	}
	return false
}

type ChallengeResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId    string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Outcome        string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	VotesSustain   int32                  `protobuf:"varint,3,opt,name=votes_sustain,json=votesSustain,proto3" json:"votes_sustain,omitempty"`
	VotesDismiss   int32                  `protobuf:"varint,4,opt,name=votes_dismiss,json=votesDismiss,proto3" json:"votes_dismiss,omitempty"`
	PenaltyApplied string                 `protobuf:"bytes,5,opt,name=penalty_applied,json=penaltyApplied,proto3" json:"penalty_applied,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChallengeResult) Reset() {
	*x = ChallengeResult{}
	mi := &file_proto_inv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResult) ProtoMessage() {}

func (x *ChallengeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResult.ProtoReflect.Descriptor instead.
func (*ChallengeResult) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{17}
}

func (x *ChallengeResult) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ChallengeResult) GetVotesSustain() int32 {
	if x != nil {
		return x.VotesSustain
	}
	return 0
}

func (x *ChallengeResult) GetVotesDismiss() int32 {
	if x != nil {
		return x.VotesDismiss
	}
	return 0
}

func (x *ChallengeResult) GetPenaltyApplied() string {
	if x != nil {
		return x.PenaltyApplied
	}
	return ""
}

type PairInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HostPeerId    string                 `protobuf:"bytes,2,opt,name=host_peer_id,json=hostPeerId,proto3" json:"host_peer_id,omitempty"`
	HostNodeId    string                 `protobuf:"bytes,3,opt,name=host_node_id,json=hostNodeId,proto3" json:"host_node_id,omitempty"`
	GuestPeerId   string                 `protobuf:"bytes,4,opt,name=guest_peer_id,json=guestPeerId,proto3" json:"guest_peer_id,omitempty"`
	GuestNodeId   string                 `protobuf:"bytes,5,opt,name=guest_node_id,json=guestNodeId,proto3" json:"guest_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairInvite) Reset() {
	*x = PairInvite{}
	mi := &file_proto_inv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairInvite) ProtoMessage() {}

func (x *PairInvite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairInvite.ProtoReflect.Descriptor instead.
func (*PairInvite) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{18}
}

func (x *PairInvite) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PairInvite) GetHostPeerId() string {
	if x != nil {
		return x.HostPeerId
	}
	return ""
}

func (x *PairInvite) GetHostNodeId() string {
	if x != nil {
		return x.HostNodeId
	}
	return ""
}

func (x *PairInvite) GetGuestPeerId() string {
	if x != nil {
		return x.GuestPeerId
	}
	return ""
}

func (x *PairInvite) GetGuestNodeId() string {
	if x != nil {
		return x.GuestNodeId
	}
	return ""
}

type PairAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GuestPeerId   string                 `protobuf:"bytes,2,opt,name=guest_peer_id,json=guestPeerId,proto3" json:"guest_peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairAccept) Reset() {
	*x = PairAccept{}
	mi := &file_proto_inv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairAccept) ProtoMessage() {}

func (x *PairAccept) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairAccept.ProtoReflect.Descriptor instead.
func (*PairAccept) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{19}
}

func (x *PairAccept) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PairAccept) GetGuestPeerId() string {
	if x != nil {
		return x.GuestPeerId
	}
	return ""
}

type PairEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EndedBy       string                 `protobuf:"bytes,2,opt,name=ended_by,json=endedBy,proto3" json:"ended_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairEnd) Reset() {
	*x = PairEnd{}
	mi := &file_proto_inv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairEnd) ProtoMessage() {}

func (x *PairEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairEnd.ProtoReflect.Descriptor instead.
func (*PairEnd) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{20}
}

func (x *PairEnd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PairEnd) GetEndedBy() string {
	if x != nil {
		return x.EndedBy
	}
	return ""
}

type PairEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventKind     string                 `protobuf:"bytes,2,opt,name=event_kind,json=eventKind,proto3" json:"event_kind,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairEvent) Reset() {
	*x = PairEvent{}
	mi := &file_proto_inv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairEvent) ProtoMessage() {}

func (x *PairEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairEvent.ProtoReflect.Descriptor instead.
func (*PairEvent) Descriptor() ([]byte, []int) {
	return file_proto_inv_proto_rawDescGZIP(), []int{21}
}

func (x *PairEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PairEvent) GetEventKind() string {
	if x != nil {
		return x.EventKind
	}
	return ""
}

func (x *PairEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

var File_proto_inv_proto protoreflect.FileDescriptor

const file_proto_inv_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/inv.proto\x12\x03inv\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\n" +
	"\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tfrom_peer\x18\x02 \x01(\tR\bfromPeer\x12\x17\n" +
	"\ato_peer\x18\x03 \x01(\tR\x06toPeer\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x128\n" +
	"\rsignal_change\x18\n" +
	" \x01(\v2\x11.inv.SignalChangeH\x00R\fsignalChange\x125\n" +
	"\fsignal_sweep\x18\v \x01(\v2\x10.inv.SignalSweepH\x00R\vsignalSweep\x12,\n" +
	"\tquery_ask\x18\x0e \x01(\v2\r.inv.QueryAskH\x00R\bqueryAsk\x128\n" +
	"\rquery_respond\x18\x0f \x01(\v2\x11.inv.QueryRespondH\x00R\fqueryRespond\x12F\n" +
	"\x11trace_resolve_req\x18\x10 \x01(\v2\x18.inv.TraceResolveRequestH\x00R\x0ftraceResolveReq\x12I\n" +
	"\x12trace_resolve_resp\x18\x11 \x01(\v2\x19.inv.TraceResolveResponseH\x00R\x10traceResolveResp\x12\x1c\n" +
	"\x03ack\x18\x14 \x01(\v2\b.inv.AckH\x00R\x03ack\x12\"\n" +
	"\x05error\x18\x15 \x01(\v2\n" +
	".inv.ErrorH\x00R\x05error\x12>\n" +
	"\x0fproposal_create\x18\x16 \x01(\v2\x13.inv.ProposalCreateH\x00R\x0eproposalCreate\x128\n" +
	"\rproposal_vote\x18\x17 \x01(\v2\x11.inv.ProposalVoteH\x00R\fproposalVote\x12>\n" +
	"\x0fproposal_result\x18\x18 \x01(\v2\x13.inv.ProposalResultH\x00R\x0eproposalResult\x128\n" +
	"\rtally_request\x18\x19 \x01(\v2\x11.inv.TallyRequestH\x00R\ftallyRequest\x12;\n" +
	"\x0epeer_handshake\x18\x1a \x01(\v2\x12.inv.PeerHandshakeH\x00R\rpeerHandshake\x12A\n" +
	"\x10challenge_create\x18\x1e \x01(\v2\x14.inv.ChallengeCreateH\x00R\x0fchallengeCreate\x12G\n" +
	"\x12challenge_response\x18\x1f \x01(\v2\x16.inv.ChallengeResponseH\x00R\x11challengeResponse\x12;\n" +
	"\x0echallenge_vote\x18  \x01(\v2\x12.inv.ChallengeVoteH\x00R\rchallengeVote\x12A\n" +
	"\x10challenge_result\x18! \x01(\v2\x14.inv.ChallengeResultH\x00R\x0fchallengeResult\x122\n" +
	"\vpair_invite\x18( \x01(\v2\x0f.inv.PairInviteH\x00R\n" +
	"pairInvite\x122\n" +
	"\vpair_accept\x18) \x01(\v2\x0f.inv.PairAcceptH\x00R\n" +
	"pairAccept\x12)\n" +
	"\bpair_end\x18* \x01(\v2\f.inv.PairEndH\x00R\apairEnd\x12/\n" +
	"\n" +
	"pair_event\x18+ \x01(\v2\x0e.inv.PairEventH\x00R\tpairEventB\t\n" +
	"\apayload\"\x98\x01\n" +
	"\fSignalChange\x12$\n" +
	"\x0esource_item_id\x18\x01 \x01(\tR\fsourceItemId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_item_id\x18\x03 \x01(\tR\ftargetItemId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x80\x01\n" +
	"\vSignalSweep\x12!\n" +
	"\fexternal_ref\x18\x01 \x01(\tR\vexternalRef\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\x12(\n" +
	"\x10matched_item_ids\x18\x03 \x03(\tR\x0ematchedItemIds\"v\n" +
	"\bQueryAsk\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x19\n" +
	"\basker_id\x18\x02 \x01(\tR\aaskerId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\"y\n" +
	"\fQueryRespond\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12!\n" +
	"\fresponder_id\x18\x02 \x01(\tR\vresponderId\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12\x13\n" +
	"\x05is_ai\x18\x04 \x01(\bR\x04isAi\".\n" +
	"\x13TraceResolveRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"\xbc\x01\n" +
	"\x14TraceResolveResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bvertical\x18\x06 \x01(\tR\bvertical\x12\x14\n" +
	"\x05found\x18\a \x01(\bR\x05found\"+\n" +
	"\x03Ack\x12$\n" +
	"\x0eref_message_id\x18\x01 \x01(\tR\frefMessageId\"[\n" +
	"\x05Error\x12$\n" +
	"\x0eref_message_id\x18\x01 \x01(\tR\frefMessageId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb6\x01\n" +
	"\rPeerHandshake\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bvertical\x18\x04 \x01(\tR\bvertical\x12\x18\n" +
	"\aproject\x18\x05 \x01(\tR\aproject\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x13\n" +
	"\x05is_ai\x18\a \x01(\bR\x04isAi\"\xa5\x02\n" +
	"\x0eProposalCreate\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rproposer_peer\x18\x05 \x01(\tR\fproposerPeer\x12\x1d\n" +
	"\n" +
	"owner_peer\x18\x06 \x01(\tR\townerPeer\x12*\n" +
	"\x11affected_item_ids\x18\a \x03(\tR\x0faffectedItemIds\x126\n" +
	"\bdeadline\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xb2\x01\n" +
	"\fProposalVote\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x1d\n" +
	"\n" +
	"voter_peer\x18\x02 \x01(\tR\tvoterPeer\x12\x19\n" +
	"\bvoter_id\x18\x03 \x01(\tR\avoterId\x12\x1a\n" +
	"\bdecision\x18\x04 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x13\n" +
	"\x05is_ai\x18\x06 \x01(\bR\x04isAi\"\xd9\x01\n" +
	"\x0eProposalResult\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x1b\n" +
	"\tvotes_for\x18\x03 \x01(\x05R\bvotesFor\x12#\n" +
	"\rvotes_against\x18\x04 \x01(\x05R\fvotesAgainst\x12%\n" +
	"\x0etotal_eligible\x18\x05 \x01(\x05R\rtotalEligible\x12!\n" +
	"\fowner_vetoed\x18\x06 \x01(\bR\vownerVetoed\"/\n" +
	"\fTallyRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\"\xc7\x02\n" +
	"\x0fChallengeCreate\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12'\n" +
	"\x0fchallenger_peer\x18\x03 \x01(\tR\x0echallengerPeer\x12'\n" +
	"\x0fchallenged_peer\x18\x04 \x01(\tR\x0echallengedPeer\x12$\n" +
	"\x0etarget_item_id\x18\x05 \x01(\tR\ftargetItemId\x12&\n" +
	"\x0ftarget_trace_id\x18\x06 \x01(\tR\rtargetTraceId\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1a\n" +
	"\bevidence\x18\b \x01(\tR\bevidence\x12)\n" +
	"\x10deadline_seconds\x18\t \x01(\x03R\x0fdeadlineSeconds\"x\n" +
	"\x11ChallengeResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1a\n" +
	"\bevidence\x18\x02 \x01(\tR\bevidence\x12$\n" +
	"\rjustification\x18\x03 \x01(\tR\rjustification\"\x9a\x01\n" +
	"\rChallengeVote\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1d\n" +
	"\n" +
	"voter_peer\x18\x02 \x01(\tR\tvoterPeer\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x13\n" +
	"\x05is_ai\x18\x05 \x01(\bR\x04isAi\"\xc1\x01\n" +
	"\x0fChallengeResult\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12#\n" +
	"\rvotes_sustain\x18\x03 \x01(\x05R\fvotesSustain\x12#\n" +
	"\rvotes_dismiss\x18\x04 \x01(\x05R\fvotesDismiss\x12'\n" +
	"\x0fpenalty_applied\x18\x05 \x01(\tR\x0epenaltyApplied\"\xb7\x01\n" +
	"\n" +
	"PairInvite\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\fhost_peer_id\x18\x02 \x01(\tR\n" +
	"hostPeerId\x12 \n" +
	"\fhost_node_id\x18\x03 \x01(\tR\n" +
	"hostNodeId\x12\"\n" +
	"\rguest_peer_id\x18\x04 \x01(\tR\vguestPeerId\x12\"\n" +
	"\rguest_node_id\x18\x05 \x01(\tR\vguestNodeId\"O\n" +
	"\n" +
	"PairAccept\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\"\n" +
	"\rguest_peer_id\x18\x02 \x01(\tR\vguestPeerId\"C\n" +
	"\aPairEnd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bended_by\x18\x02 \x01(\tR\aendedBy\"l\n" +
	"\tPairEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_kind\x18\x02 \x01(\tR\teventKind\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJsonB)Z'github.com/cuongtran/my-inventory/protob\x06proto3"

var (
	file_proto_inv_proto_rawDescOnce sync.Once
	file_proto_inv_proto_rawDescData []byte
)

func file_proto_inv_proto_rawDescGZIP() []byte {
	file_proto_inv_proto_rawDescOnce.Do(func() {
		file_proto_inv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inv_proto_rawDesc), len(file_proto_inv_proto_rawDesc)))
	})
	return file_proto_inv_proto_rawDescData
}

var file_proto_inv_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_inv_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: inv.Envelope
	(*SignalChange)(nil),          // 1: inv.SignalChange
	(*SignalSweep)(nil),           // 2: inv.SignalSweep
	(*QueryAsk)(nil),              // 3: inv.QueryAsk
	(*QueryRespond)(nil),          // 4: inv.QueryRespond
	(*TraceResolveRequest)(nil),   // 5: inv.TraceResolveRequest
	(*TraceResolveResponse)(nil),  // 6: inv.TraceResolveResponse
	(*Ack)(nil),                   // 7: inv.Ack
	(*Error)(nil),                 // 8: inv.Error
	(*PeerHandshake)(nil),         // 9: inv.PeerHandshake
	(*ProposalCreate)(nil),        // 10: inv.ProposalCreate
	(*ProposalVote)(nil),          // 11: inv.ProposalVote
	(*ProposalResult)(nil),        // 12: inv.ProposalResult
	(*TallyRequest)(nil),          // 13: inv.TallyRequest
	(*ChallengeCreate)(nil),       // 14: inv.ChallengeCreate
	(*ChallengeResponse)(nil),     // 15: inv.ChallengeResponse
	(*ChallengeVote)(nil),         // 16: inv.ChallengeVote
	(*ChallengeResult)(nil),       // 17: inv.ChallengeResult
	(*PairInvite)(nil),            // 18: inv.PairInvite
	(*PairAccept)(nil),            // 19: inv.PairAccept
	(*PairEnd)(nil),               // 20: inv.PairEnd
	(*PairEvent)(nil),             // 21: inv.PairEvent
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
}
var file_proto_inv_proto_depIdxs = []int32{
	22, // 0: inv.Envelope.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: inv.Envelope.signal_change:type_name -> inv.SignalChange
	2,  // 2: inv.Envelope.signal_sweep:type_name -> inv.SignalSweep
	3,  // 3: inv.Envelope.query_ask:type_name -> inv.QueryAsk
	4,  // 4: inv.Envelope.query_respond:type_name -> inv.QueryRespond
	5,  // 5: inv.Envelope.trace_resolve_req:type_name -> inv.TraceResolveRequest
	6,  // 6: inv.Envelope.trace_resolve_resp:type_name -> inv.TraceResolveResponse
	7,  // 7: inv.Envelope.ack:type_name -> inv.Ack
	8,  // 8: inv.Envelope.error:type_name -> inv.Error
	10, // 9: inv.Envelope.proposal_create:type_name -> inv.ProposalCreate
	11, // 10: inv.Envelope.proposal_vote:type_name -> inv.ProposalVote
	12, // 11: inv.Envelope.proposal_result:type_name -> inv.ProposalResult
	13, // 12: inv.Envelope.tally_request:type_name -> inv.TallyRequest
	9,  // 13: inv.Envelope.peer_handshake:type_name -> inv.PeerHandshake
	14, // 14: inv.Envelope.challenge_create:type_name -> inv.ChallengeCreate
	15, // 15: inv.Envelope.challenge_response:type_name -> inv.ChallengeResponse
	16, // 16: inv.Envelope.challenge_vote:type_name -> inv.ChallengeVote
	17, // 17: inv.Envelope.challenge_result:type_name -> inv.ChallengeResult
	18, // 18: inv.Envelope.pair_invite:type_name -> inv.PairInvite
	19, // 19: inv.Envelope.pair_accept:type_name -> inv.PairAccept
	20, // 20: inv.Envelope.pair_end:type_name -> inv.PairEnd
	21, // 21: inv.Envelope.pair_event:type_name -> inv.PairEvent
	22, // 22: inv.ProposalCreate.deadline:type_name -> google.protobuf.Timestamp
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_inv_proto_init() }
func file_proto_inv_proto_init() {
	if File_proto_inv_proto != nil {
		return
	}
	file_proto_inv_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_SignalChange)(nil),
		(*Envelope_SignalSweep)(nil),
		(*Envelope_QueryAsk)(nil),
		(*Envelope_QueryRespond)(nil),
		(*Envelope_TraceResolveReq)(nil),
		(*Envelope_TraceResolveResp)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_ProposalCreate)(nil),
		(*Envelope_ProposalVote)(nil),
		(*Envelope_ProposalResult)(nil),
		(*Envelope_TallyRequest)(nil),
		(*Envelope_PeerHandshake)(nil),
		(*Envelope_ChallengeCreate)(nil),
		(*Envelope_ChallengeResponse)(nil),
		(*Envelope_ChallengeVote)(nil),
		(*Envelope_ChallengeResult)(nil),
		(*Envelope_PairInvite)(nil),
		(*Envelope_PairAccept)(nil),
		(*Envelope_PairEnd)(nil),
		(*Envelope_PairEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inv_proto_rawDesc), len(file_proto_inv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_inv_proto_goTypes,
		DependencyIndexes: file_proto_inv_proto_depIdxs,
		MessageInfos:      file_proto_inv_proto_msgTypes,
	}.Build()
	File_proto_inv_proto = out.File
	file_proto_inv_proto_goTypes = nil
	file_proto_inv_proto_depIdxs = nil
}
